id: IA86A66C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:18:49+00:00'
last_modified: '2022-06-09T05:10:59.307859+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26039
  title: བདག་འདྲ་ཐེག་གླིང་འགྲོ་དོན་མཐར་ཕྱིན་ནམ་ཨོ་རྒྱན་དྲི་མེད་གླིང་པ་གར་དབང་བདུད་འདུལ་ལས་རབ་རྩལ་དུ་འབོད་པའི་རྣམ་ཐར་མགུར་འབུམ་དོན་གྱི་མེ་ལོང་ཚངས་པའི་སྒྲ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    10A1:
      image_group_id: I1KG9621
      title: ''
      total_pages: 352
      order: 1
      base_file: 10A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
