id: IA86A66C1
legacy_id: P008198
ocr_import_info:
  bdrc_scan_id: W26039
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:16:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:22:34.578390+00:00'
last_modified: 2022-09-02 14:22:46.980109
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26039
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26039
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདག་འདྲ་ཐེག་གླིང་འགྲོ་དོན་མཐར་ཕྱིན་ནམ་ཨོ་རྒྱན་དྲི་མེད་གླིང་པ་གར་དབང་བདུད་འདུལ་ལས་རབ་རྩལ་དུ་འབོད་པའི་རྣམ་ཐར་མགུར་འབུམ་དོན་གྱི་མེ་ལོང་ཚངས་པའི་སྒྲ་དབྱངས།
  author: དྲི་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7849917279888893
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I1KG9621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9621
      total_pages: 352
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9621.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7849917279888893
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
